# Generated by Django 2.2.7 on 2019-12-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='info',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
